name: epic-freebies-helper

services:
  epic-freebies-helper:
    image: ghcr.io/thewisewolfholo/epic-freebies-helper:latest
    restart: always
    container_name: epic-freebies-helper

    env_file:
      - .env
    environment:
      TZ: Asia/Shanghai

    volumes:
      - "./volumes/:/app/app/volumes/"

    entrypoint: [ "/usr/bin/tini", "--" ]
    command: xvfb-run --auto-servernum --server-num=1 --server-args='-screen 0, 1920x1080x24' uv run app/deploy.py

    mem_limit: 4g
    shm_size: '2gb'
